system:
  env: dev

spring:
  redis:
    database: 1
    host: 10.216.32.54
    port: 32548
    password: test
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.99.100:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: my-secret-pw

logging:
  level:
    com.jlh.demoworkweb.mapper: DEBUG


cors:
#  addrs: http://localhost:8081,http://localhost:8082
  addrs:
