system:
  env: dev

spring:
  redis:
    database: 0
    host: 192.168.137.101
    port: 6379
    password:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.137.101:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456

logging:
  level:
    com.jlh.demoworkweb.mapper: DEBUG


cors:
#  addrs: http://localhost:8081,http://localhost:8082
  addrs:
